In [13]:
from astroquery.splatalogue import Splatalogue
line_ids = Splatalogue.get_species_ids()

In [14]:
from astropy import units as u
test = Splatalogue.query_lines(680.35*u.GHz, 682.34*u.GHz, only_NRAO_recommended=True)
test.pprint()

species_id                        name                         chemical_name   ... sqlquery requestnumber
---------- ------------------------------------------------- ----------------- ... -------- -------------
      1044                  g-CH<sub>3</sub>CH<sub>2</sub>OH    gauche-Ethanol ...     None             0
      1044                  g-CH<sub>3</sub>CH<sub>2</sub>OH    gauche-Ethanol ...     None             0
       646                   CH<sub>2</sub><sup>13</sup>CHCN    Vinyl Cyanide  ...     None             0
       941   CH<sub>3</sub>COOH <font color="red">v=0</font>       Acetic Acid ...     None             0
      1319                                   TiO<sub>2</sub>  Titanium dioxide ...     None             0
       853                      <i>t</i>-CH<sub>2</sub>CHCHO          Propenal ...     None             0
       853                      <i>t</i>-CH<sub>2</sub>CHCHO          Propenal ...     None             0
       813   CH<sub>3</sub>OD <font color="red">v = 0</font>          Methanol ...     None             0
     21278                               HCCCH<sub>2</sub>CN Propargyl cyanide ...     None             0
      1041 CH<sub>3</sub>CN <font color="red">v8 = 1 </font>    Methyl Cyanide ...     None             0
       223                                             CNCHO Cyanoformaldehyde ...     None             0
     21278                               HCCCH<sub>2</sub>CN Propargyl cyanide ...     None             0
     21278                               HCCCH<sub>2</sub>CN Propargyl cyanide ...     None             0
       ...                                               ...               ... ...      ...           ...
       941   CH<sub>3</sub>COOH <font color="red">v=0</font>       Acetic Acid ...     None             0
     21257                       CH<sub>3</sub>SH, vt &le; 2  Methyl Mercaptan ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
     42109   CH<sub>3</sub>OD <font color="red">v = 1</font>          Methanol ...     None             0
      1277                    H<sub>2</sub>NCH<sub>2</sub>CN Aminoacetonitrile ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
Length = 2438 rows

In [15]:
import pandas as pd
test

<Table length=2438>
species_id                        name                         chemical_name   ... sqlquery requestnumber
  int32                          str99                             str39       ...  object      int32
---------- ------------------------------------------------- ----------------- ... -------- -------------
      1044                  g-CH<sub>3</sub>CH<sub>2</sub>OH    gauche-Ethanol ...     None             0
      1044                  g-CH<sub>3</sub>CH<sub>2</sub>OH    gauche-Ethanol ...     None             0
       646                   CH<sub>2</sub><sup>13</sup>CHCN    Vinyl Cyanide  ...     None             0
       941   CH<sub>3</sub>COOH <font color="red">v=0</font>       Acetic Acid ...     None             0
      1319                                   TiO<sub>2</sub>  Titanium dioxide ...     None             0
       853                      <i>t</i>-CH<sub>2</sub>CHCHO          Propenal ...     None             0
       853                      <i>t</i>-CH<sub>2</sub>CHCHO          Propenal ...     None             0
       813   CH<sub>3</sub>OD <font color="red">v = 0</font>          Methanol ...     None             0
     21278                               HCCCH<sub>2</sub>CN Propargyl cyanide ...     None             0
      1041 CH<sub>3</sub>CN <font color="red">v8 = 1 </font>    Methyl Cyanide ...     None             0
       223                                             CNCHO Cyanoformaldehyde ...     None             0
     21278                               HCCCH<sub>2</sub>CN Propargyl cyanide ...     None             0
       ...                                               ...               ... ...      ...           ...
       941   CH<sub>3</sub>COOH <font color="red">v=0</font>       Acetic Acid ...     None             0
     21257                       CH<sub>3</sub>SH, vt &le; 2  Methyl Mercaptan ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
     42109   CH<sub>3</sub>OD <font color="red">v = 1</font>          Methanol ...     None             0
      1277                    H<sub>2</sub>NCH<sub>2</sub>CN Aminoacetonitrile ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0
       758  CH<sub>2</sub>CHCN <font color="red">v= 0</font>     Vinyl Cyanide ...     None             0

In [16]:
test = test.to_pandas()

In [17]:
test['chemical_name'].value_counts().head(10)

chemical_name
Vinyl Cyanide            306
Ethyl Cyanide            241
Methyl Formate           151
Aluminum Monochloride    136
Ethyl cyanide            134
Vinyl Cyanide            103
Acetone                  101
Methyl Mercaptan          96
Propargyl cyanide         93
Acetaldehyde              93
Name: count, dtype: int64

In [23]:
frequency_ranges = [(680.35, 682.34), (681.29, 683.15), (688.19, 690.06)]  # Example range pairs

all_lines = []
#loop through the freq pairs
for start_freq, end_freq in frequency_ranges:
    #Splat query
    lines = Splatalogue.query_lines(start_freq*u.GHz, end_freq*u.GHz, only_NRAO_recommended=True)
    lines_df = lines.to_pandas()
  
    #append df to list
    all_lines.append(lines_df)

#concatenate all df into big df
combined_df = pd.concat(all_lines, ignore_index=True)

combined_df['chemical_name'] = combined_df['chemical_name'].str.lower()
combined_df

,species_id,name,chemical_name,resolved_QNs,linelist,LovasASTIntensity,lower_state_energy,upper_state_energy,sijmu2,sij,...,lineid,transition_in_space,transition_in_G358,obsref_Lovas_NIST,source_Lovas_NIST,telescope_Lovas_NIST,transitionBandColor,searchErrorMessage,sqlquery,requestnumber
0,1044,g-CH<sub>3</sub>CH<sub>2</sub>OH,gauche-ethanol,"31(27, 4)-32(26, 6), v<sub>t</sub>= 0- 1",JPL,,920.4529,943.14694,0.28407,0.000,...,4297320,0,0,,,,datatablepastelblue,,None,0
1,1044,g-CH<sub>3</sub>CH<sub>2</sub>OH,gauche-ethanol,"31(27, 4)-32(26, 6), v<sub>t</sub>= 0- 1",JPL,,920.4529,943.14694,0.28407,0.000,...,4297321,0,0,,,,datatablepastelblue,,None,0
2,646,CH<sub>2</sub><sup>13</sup>CHCN,vinyl cyanide,"72( 8,65)-71( 8,64)",JPL,,898.8871,921.58117,1034.96300,76.424,...,6779043,0,0,,,,datatablepastelblue,,None,0
3,941,"CH<sub>3</sub>COOH <font color=""red"">v=0</font>",acetic acid,"48(34,14) - 48(29,19), E",CDMS,,738.6437,761.33785,0.04490,0.000,...,15490219,0,0,,,,datatablepastelblue,,None,0
4,1319,TiO<sub>2</sub>,titanium dioxide,"48( 3,45)-47( 4,44)",CDMS,,565.1974,587.89158,1393.17983,0.000,...,13397517,0,0,,,,datatablepastelblue,,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6791,21257,"CH<sub>3</sub>SH, vt &le; 2",methyl mercaptan,"66(5,61) - 66(-4,63) E, v<sub>t</sub>=1",CDMS,,2097.2585,2120.27622,2.46792,0.000,...,13842951,0,0,,,,datatablepastelblue,,None,0
6792,21182,"CH3CH2CN, v20 = 1-A",ethyl cyanide,"76(6,70) - 75(6,69)",CDMS,,1261.5057,1284.52351,1099.47280,0.000,...,10619769,0,0,,,,datatablepastelblue,,None,0
6793,646,CH<sub>2</sub><sup>13</sup>CHCN,vinyl cyanide,"85(18,67)-86(17,70)",JPL,,1596.3196,1619.33750,10.76424,0.000,...,6779221,0,0,,,,datatablepastelblue,,None,0
6794,646,CH<sub>2</sub><sup>13</sup>CHCN,vinyl cyanide,"85(18,68)-86(17,69)",JPL,,1596.3196,1619.33750,10.76424,0.000,...,6779222,0,0,,,,datatablepastelblue,,None,0
6795,55,"CH<sub>3</sub>OH <font color=""red"">v<sub>t</su...",methanol,27(15) -26(17) E1 v<sub>t</sub>=1 - v<sub>t</...,JPL,,1557.3860,1580.40391,0.00012,0.000,...,11808342,0,0,,,,datatablepastelblue,,None,0

In [25]:
print(combined_df.columns)

Index(['species_id', 'name', 'chemical_name', 'resolved_QNs', 'linelist',
       'LovasASTIntensity', 'lower_state_energy', 'upper_state_energy',
       'sijmu2', 'sij', 'aij', 'intintensity', 'Lovas_NRAO', 'orderedfreq',
       'lower_state_energy_K', 'upper_state_energy_K', 'orderedFreq',
       'measFreq', 'upperStateDegen', 'moleculeTag', 'qnCode',
       'labref_Lovas_NIST', 'rel_int_HFS_Lovas', 'unres_quantum_numbers',
       'lineid', 'transition_in_space', 'transition_in_G358',
       'obsref_Lovas_NIST', 'source_Lovas_NIST', 'telescope_Lovas_NIST',
       'transitionBandColor', 'searchErrorMessage', 'sqlquery',
       'requestnumber'],
      dtype='object')

In [66]:
combined_df['upperStateDegen'].unique()

array(['63', '145', '97', ' 97 ', '29', '31', '753', '150', '119', '213',
       '81', '157 ', '158', '166', '153', '43', '67', '300', '459', '69',
       '91', '226', '78', '54', '83', '110', '55', '99', '747', '254',
       '77', '115', '153 ', '35', '45', '61', '157', '65', '125', '42',
       '46', '49', '121', '127 ', '125 ', '129 ', '122', '162', '142',
       '149', '174', '151', '155', '143', '33', '161', '47', '93', '147',
       '315', '73', '75', ' 93 ', '114', '51', '212', '165', '37', '52',
       '98', '113', '3', '19', '84', '117 ', '79', '111', '175', '135',
       '999', '197 ', '193 ', '195 ', '87', '30', '32', '28', '34', '53',
       '146', '148', '144', '207', '17', '217', '678', '236', '741', '9',
       ' 91 ', ' 95 ', '59', '468', '12', '195', '524', '41', '14', '444',
       '16', '690', '414', '71', '149 ', '151 ', '121 ', '123 ', '260',
       '291', '147 ', '170', '102', '143 ', '141 ', '145 ', '7', '139',
       '276', '130', '57', '197', '222', '1', '89', '105', '85', '196',
       '204', '435', '702', '654', '321', '210', '95', ' 89 ', '141',
       '117', '25', '127', '27', ' 17 ', ' 21 ', ' 19 ', '137', '525',
       '23', '436', '218', '199', ' 87 ', '191', '765', ' 33 ', '223 ',
       '182', '15', '540', '107', '452', '227 ', '225 ', '58', '26',
       '399', '278', '834', '556', '179', '138', '111 ', '115 ', '113 ',
       '13', ' 55 ', '159', '183 ', '179 ', '181 ', '173', '735', '39',
       '109', '312', '460', '129', '171', '133', '327', '205 ', '207 ',
       '209 ', '126', ' 29 ', '189', '178', '750', '500', '250', '228',
       '201', '201 ', '203 ', '62', '230', '72', '74', '76', '169', '22',
       '24', ' 75 ', '243', ' 73 ', ' 77 ', '177', '123', '38', '86',
       '324', '411', '119 ', '108', '106', '133 ', '167', '185 ', '185',
       '', '333', '630', '612', '308', '5', '82', '155 ', '183', '135 ',
       '36', '252', '101', '249', '316', '11', '258', '6', '450', '101 ',
       ' 99 ', '103 ', '378', '292', '103', '759', '225', '163', '181',
       '203', '233', ' 63 ', ' 59 ', ' 61 ', '339', '255', ' 71 ', ' 69 ',
       '66', ' 38 ', '221 ', '217 ', '219 ', '131', '105 ', '309', '10',
       '18', '132', '438', '465', '140', '516', '241', '193', '247',
       '285', '345', '209', '666', '603', '152', ' 65 ', '187 ', ' 27 ',
       ' 31 ', '40', ' 67 ', '21', '70', '131 ', '20', '771', '223',
       '363', ' 53 ', ' 45 ', '104', '351', '109 ', ' 25 ', '515', ' 49 ',
       ' 51 ', ' 79 ', ' 81 ', '762', '508', '159 ', '231', '650', '194',
       '357', '390', '188', '191 ', '189 ', '180', '253 ', '229 ', '380',
       '777', '118', '134', '199 ', '161 ', '163 ', ' 83 ', ' 57 ', '404',
       '219', '154', '244', '573', '187', '227', ' 47 ', '495', '342',
       '205', '235', '645', '175 ', '171 ', '173 ', ' 35 ', '211', '783',
       '412', '369', '215 ', '303', '572', '912', '555', '94', '372',
       '355', '305', '375', '600', '221', '795', '229', '519', '237',
       '265 ', '738', '234', '245 ', '241 ', '243 ', '492', '246', '136',
       '483', '107 ', '186', '605', '642', '165 ', '441', '447', '428',
       '214', '255 ', '124', '388', '164', '220', '139 ', '294', '489',
       '532', '784', '801', '445', '50', '116', '273', '455', '215',
       '417', ' 23 ', '549', '710', '426', '284', '807', '477', '429',
       '501', '68', '420', '239', '263 ', '2', '90', '128', '235 ', '206',
       '364', '507', '393', '813', ' 41 ', ' 43 ', '618', '177 ', '490',
       '167 ', '156', '513', '267', '453'], dtype=object)

In [29]:
y = combined_df[(combined_df['lower_state_energy_K']>=0)&(combined_df['lower_state_energy_K']<=1000)]
y

,species_id,name,chemical_name,resolved_QNs,linelist,LovasASTIntensity,lower_state_energy,upper_state_energy,sijmu2,sij,...,lineid,transition_in_space,transition_in_G358,obsref_Lovas_NIST,source_Lovas_NIST,telescope_Lovas_NIST,transitionBandColor,searchErrorMessage,sqlquery,requestnumber
4,1319,TiO<sub>2</sub>,titanium dioxide,"48( 3,45)-47( 4,44)",CDMS,,565.1974,587.89158,1393.17983,0.000,...,13397517,0,0,,,,datatablepastelblue,,None,0
5,853,<i>t</i>-CH<sub>2</sub>CHCHO,propenal,"14(10,4) - 15(9,7)",CDMS,,151.4795,174.17373,0.19932,0.000,...,7221847,0,0,,,,datatablepastelblue,,None,0
6,853,<i>t</i>-CH<sub>2</sub>CHCHO,propenal,"14(10,5) - 15(9,6)",CDMS,,151.4795,174.17373,0.19932,0.000,...,7221848,0,0,,,,datatablepastelblue,,None,0
7,813,"CH<sub>3</sub>OD <font color=""red"">v = 0</font>",methanol,"15( 4,11)-14( 4,10) A",CDMS,,205.6648,228.35903,9.78992,14.065,...,15553466,0,0,,,,datatablepastelblue,,None,0
10,223,CNCHO,cyanoformaldehyde,"59( 6,54)-59( 5,55)",CDMS,,623.3434,646.03777,183.75700,31.902,...,399964,0,0,,,,datatablepastelblue,,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6784,717,CH<sub>3</sub><sup>13</sup>CH<sub>2</sub>CN,ethyl cyanide,"38(24,14) - 39(23,17)",CDMS,,626.6337,649.65121,2.37163,0.000,...,14745073,0,0,,,,datatablepastelblue,,None,0
6785,717,CH<sub>3</sub><sup>13</sup>CH<sub>2</sub>CN,ethyl cyanide,"38(24,15) - 39(23,16)",CDMS,,626.6337,649.65121,2.37163,0.000,...,14745074,0,0,,,,datatablepastelblue,,None,0
6786,551,<sup>13</sup>CH<sub>2</sub>CHCN,vinyl cyanide,"32( 5,28)-32( 3,29)",JPL,,176.9759,199.99342,0.09292,0.000,...,6722369,0,0,,,,datatablepastelblue,,None,0
6788,21209,i-C3H7CN,iso-propyl cyanide,"30(28,2) - 29(26,3)",CDMS,,201.3299,224.34749,0.36372,0.000,...,11347339,0,0,,,,datatablepastelblue,,None,0
6789,21209,i-C3H7CN,iso-propyl cyanide,"30(28,3) - 29(26,4)",CDMS,,201.3299,224.34749,0.36372,0.000,...,11347340,0,0,,,,datatablepastelblue,,None,0

In [31]:
y[['moleculeTag','chemical_name']].value_counts()

moleculeTag  chemical_name
62005        aluminum monochloride         272
53001        vinyl cyanide                 195
60523        acetic acid                   178
44003        acetaldehyde                  160
0            methyl formate                135
                                          ...
42501        ketene                          1
43510        cyanic acid                     1
45506        thioformylium                   1
45520        o-protonated nitrous oxide      1
39509        cyclopropenylidene              1
Name: count, Length: 113, dtype: int64

In [33]:
combined_df[['moleculeTag','chemical_name']].value_counts()

moleculeTag  chemical_name
 53001       vinyl cyanide                    967
 44003       acetaldehyde                     335
 0           methyl formate                   317
 62005       aluminum monochloride            272
 60523       acetic acid                      270
                                             ...
 44501       carbon monosulfide                 1
 44505       silicon monoxide                   1
 46503       silicon monoxide (global fit)      1
 45504       silicon monoxide (global fit)      1
-74505       potassium chloride                 1
Name: count, Length: 154, dtype: int64

In [35]:
def q25(x):
    return x.quantile(0.25)

def q50(x):
    return x.quantile(0.5)
    
def q75(x):
    return x.quantile(0.75)

In [37]:
x=pd.DataFrame(combined_df.groupby('chemical_name').agg(count=('chemical_name', 'count'), 
    lower_state_energy_K_25=('lower_state_energy_K', q25), 
    lower_state_energy_K_50=('lower_state_energy_K', q50), 
    lower_state_energy_K_75=('lower_state_energy_K', q75)).sort_values(by='count',ascending = False).reset_index())#.head(20).round(2)
x

,chemical_name,count,lower_state_energy_K_25,lower_state_energy_K_50,lower_state_energy_K_75
0,ethyl cyanide,1138,1055.90627,1381.246935,2168.408127
1,vinyl cyanide,967,1240.27081,1579.372180,2801.145320
2,methyl formate,449,522.25495,1023.314950,1259.256950
3,acetaldehyde,335,539.99261,1022.834170,1523.928800
4,vinyl cyanide,307,1219.87936,1739.705830,2417.412125
...,...,...,...,...,...
82,thioformylium,1,245.70428,245.704280,245.704280
83,silicon monosulfide,1,611.95277,611.952770,611.952770
84,"3-thioxo-1,2-propadieylidene",1,1963.23211,1963.232110,1963.232110
85,o-protonated nitrous oxide,1,526.36961,526.369610,526.369610
86,hydrogen sulfide,1,1152.87774,1152.877740,1152.877740

In [39]:
pd.DataFrame({'chemical_name': [0], 'count': [0], 'lower_state_energy_K_25': [0],'lower_state_energy_K_50': [0],'lower_state_energy_K_75': [0]})

,chemical_name,count,lower_state_energy_K_25,lower_state_energy_K_50,lower_state_energy_K_75
0,0,0,0,0,0

In [41]:
print(x['chemical_name'])

0                    ethyl cyanide
1                    vinyl cyanide
2                   methyl formate
3                     acetaldehyde
4                   vinyl cyanide
                  ...
82                   thioformylium
83           silicon monosulfide
84    3-thioxo-1,2-propadieylidene
85      o-protonated nitrous oxide
86                hydrogen sulfide
Name: chemical_name, Length: 87, dtype: object